### ISSUE TITLE
add mark "contact person"

### ISSUE THREAD

**Issue by valentinaskn** [FHTW-HWSE/projekt-group14-hospital#43]

**Comment by valentinaskn** [comment]
- **Given**: Patient had seating neighbours - **When**: An “Infectious disease” mark has been set in the patient data - **Then**: The Surrounding patients should automatically get added a “contact person” mark.


In spalte Y/N für infectious einfach ein C reinschreiben, wenn er/sie kontaktperson ist

**Comment by EmilAtic** [comment]
updateContact(main header, SeatNeighbour header) -> changes the Infection Status of the contact persons to 'C' not implemented in Main yet
